version: '3'
services: 
  backend:
    build: ./Planner  
    ports:
      - "8080:8080"
  frontend:
    build: ./foodExperienceFrontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    
